### ISSUE TITLE
dtr.discover finds folders with different state files multiple times

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#101]
When I have a folder with a `Treant` and a `Sim` object then I can discover that folder twice. I haven't played around with data in the two yet but I assume they could then both show to the same data-limbs.
I don't know yet if this is potentially problematic. It can for sure lead to some confusion if people use both sims and normal treants.

**Comment by dotsdl** [comment]
@kain88-de this isn't a problem technically, but I agree it's a confusing state for a directory to be in. A directory can contain multiple `Treant` state files and in this case using e.g. `dtr.Treant(<dirname>)` will fail with an exception saying it's ambiguous which one to use. For the case where a directory has both a `Treant` and a `Sim` state file there is no ambiguity with this kind of usage, so it still works.

`discover` looks for state files, so it's perfectly happy with multiple state files that live in the same place. I don't recommend doing this, though, since 1) it's hard to see a reason for doing it, and 2) it might not work as one expects and is confusing.

**Comment by kain88-de** [comment]
This code works fine

```python
import mdsynthesis as mds
import datreant.core as dtr

mds.Sim('.')
dtr.Treant('.')
dtr.Treant('Sim.uuid.json')
```

According to your comment on of these should fail. Which one should fail in the end?



> I don't recommend doing this, though, since 1) it's hard to see a reason for doing it, and 2) it might not work as one expects and is confusing.

I don't think people will do this on purpose but I'm very sure this will happen in the future since we already have 2 packages to create state files already and more might come in the future. Such an accident can happen and error should be thrown. Ideally discover should also handle it.
