### ISSUE TITLE
Treant creation

### ISSUE THREAD

**Issue by mimischi** [datreant/datreant.core#106]
Just started using datreant, so maybe I have not wrapped my head around the logic yet. For my use case I'd like to provide a path to a specific script. This script should then load the Treant object if the path already exists, thus not creating a new Treant.

The problem is that Treant.exists always returns True, because it will create a non-existing Treant before checking the filesystem.

```python
In [1]: import datreant.core as dtr

In [2]: ll
total 0

In [3]: dtr.Treant('some-path').exists
Out[3]: True

In [4]: ll
total 4
drwxr-xr-x 2 migecht 4096 Sep 14 16:53 some-path/
```

I would expect it to return False if the Treant does not yet exist. In the end you guys provide Treant.make() and Treant.makedirs() for the creation of new Treants, so why should a simple call of dtr.Treant() always create it immediately?

**Comment by dotsdl** [comment]
Because a `Treant` requires a state file, it will always give `True` when calling `Treant.exists`. As you pointed out, it seems strange that a `Treant` has methods like `make()` or `makedirs()` that simply will never be necessary. The reason these are here is that a `Treant` is a subclass of a `Tree`, which is the object you want to use directly here.

So you could do

```python
import datreant.core as dtr

if dtr.Tree('some-path').exists:
    treant = dtr.Treant('some-path')
```

Note that `some-path` might not be a `Treant` already, since all we tested here was whether it existed as a directory. In other words, there might not be a state file inside it.

You could also take advantage of the fact that a `Bundle` will only ever find `Treant`s, but will never create them. Say I have a bunch of trajectories `one_fish`, `two_fish`, `red_fish`, `blue_fish`, and only `red_fish` is a `Treant`:

```python
>>> dtr.Bundle('one_fish', 'two_fish', 'red_fish', 'blue_fish')
<Bundle(['red_fish'])>
```
the `Bundle` will only contain elements that are actually `Treant`s already. You could then extract out the `Treant` from the `Bundle` with indexing or however else you like.

Does that help?

**Comment by mimischi** [comment]
Yes, that clears up things nicely. I just want to make sure not to create `Treants` when providing the script with a wrong path. Thanks!
