### ISSUE TITLE
issues with unicode strings in groupby and python2

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#110]
The following code doesn't work for me.

```python
b.categories.groupby('key')['val']
```

This does

```python
b.categories.groupby('key')[u'val']
```

The only difference is that I explicitly say that `'val'` is a unicode string. It would be nice if we could make it work without having to specify that.

**Comment by dotsdl** [comment]
Just tried this in Python 2.7.12, and this issue does not show up for me. Since `b.categories.groupby('key')` returns a dict, this would be a consequence to how dicts treat keys that are in Unicode. Which Python version are you using?

One solution is that we could cast the string keys of the dict groupby outputs into ASCII strings, but this could have other issues for non ASCII characters.

**Comment by kain88-de** [comment]
I'll try to come up with a minimal example. I definitely noticed it with two keys one string and one numeric.

**Comment by kain88-de** [comment]
hm weird I can't reproduce my error. Maybe I made another mistake
