### ISSUE TITLE
Tree.make doesn't create folder 

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#112]
I would expect the following code to produce a folder since the tree gives me a view of the directories

``` python
import datreant.core as dtr

treant = dtr.Treant('.')
tree = treant.tree['foo']

tree.make()
```

But `treant.tree['foo']` returns a Leave and not a Tree object. I realize this is the behavior of Tree that kind of makes sense but it's still un intuitive. My main confusion about this is that the docs say Tree is only a view of the directories in the treant.

_btw_ the follwoing works to create a directory.

``` python
tree = treant.tree['foo/']
tree.make()
```

**Comment by dotsdl** [comment]
This line:

```python
tree = treant.tree['foo']
```
returns a Leaf object, because ``treant.tree`` gives a ``Tree``, so doing ``__getitem__`` with a path that doesn't exist without an ending '/' defaults to giving a ``Leaf``. I think part of the confusion is the use of ``tree`` here. Note that you can do the same thing as above with:

```python
tree = treant['foo']
```
which also returns a ``Leaf`` if "foo" doesn't point to an existing file or directory. Does this make more sense? Is there something specific we can do to improve this?

> My main confusion about this is that the docs say Tree is only a view of the directories in the treant.

Ah, I think this is the point of confusion. ``Treant.trees`` (not ``Treant.tree``) gives back a ``View`` (literally) of the existing directories in the ``Treant``. So, say your ``treant`` had an existing directory "foo", then doing:

```python
treant.trees['foo']
```
Would give back a ``View`` of all directories with the name "foo" in that ``View`` as a ``View`` itself. Does this make sense? A ``View`` behaves similarly to a ``Bundle``, but for ``Leaf`` and ``Tree`` objects.

**Comment by kain88-de** [comment]
OK this means everything works as intended just that the options that exist are confusing. 

To me the `t.tree` meant I only look at folders and not  the total possible content of the current folder.  This is to say I would like from a semantic point of view that `t.tree` only works on folders and `t.leaves` only works on files. This gives me a clearer distinction then just a trailing backslash. 

Or if you don't want to do that just make a public attribute  called `t.view` to show we can look into the content of the treant folder and do not distinguish between folders and files (which the attributes trees/leaves suggest to me). 

I hope that makes my point clear.

**Comment by dotsdl** [comment]
Hmmm...yeah I can see the confusion I think, but not sure of the best way forward given the objects already present in the library. Let me lay out the API elements we're dealing with, here:

<dl>
  <dt>``Treant.tree``</dt>
  <dd>returns a ``Tree`` object pointing to the ``Treant``s directory</dd>
  <dt>``Treant.children``</dt>
  <dd>returns a ``View`` giving all directories and files present in the ``Treant``'s directory as ``Tree`` and ``Leaf`` objects, respectively (not recursive)</dd>
  <dt>``Treant.trees``</dt>
  <dd>returns a ``View`` giving only the directories present in the ``Treant``'s directory as ``Tree`` objects (not recursive)</dd>
  <dt>``Treant.leaves``</dt>
  <dd>returns a ``View`` giving only the files present in the ``Treant``'s directory as ``Leaf`` objects (not recursive)</dd>
  <dt>``Treant.treants``</dt>
  <dd>returns a ``Bundle`` giving ``Treant``'s present in the ``Treant``'s directory (not recursive)</dd>
  <dt>``Treant.parent``</dt>
  <dd>returns a ``Tree`` object pointing to the ``Treant``s parent directory</dd>
</dl>

A bit off topic, but we may remove the ``Treant.treants`` property since this is confusing (#114), and using ``dtr.discover(treant)`` or ``mds.discover(treant)`` already gives clearer functionality.

What, if anything, do we want to change from this current API?

**Comment by kain88-de** [comment]
**Treant.tree**: 
So this is the one I need when I want to do modifications to the underlying file system.

**Treant.children**, **Treant.trees**, **Treant.leaves**
So those are all views. You can't use them to change the file system right? If so it makes it hard for me to remember that. Just the trailing *s* isn't enough of a hint for me when I glance over code. Also why the distinction at the treant level. Why not `t.children.trees` and `t.children.leaves`. Or `t.view.tree` this makes is super clear to my brain that I have a view of tree objects even if I'm sleep deprived. 

**Treant.parent**: 
Does that even make sense? Why wouldn't it return a Treant? Otherwise t.tree.parent would seem more logical to me.
