### ISSUE TITLE
categories should only check if `value` is json serializable

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#118]
Right now we are very strict with the value types we allow for a categorie. I would say we can just check that it's json serializable to allow for greater flexiblility.

**Comment by dotsdl** [comment]
This isn't quite so simple, because for aggregate operations representation then becomes complicated. It could be done, but it does complicate things like ``groupby`` where we return a dictionary giving category values as keys. Some objects such as a list aren't hashable so they wouldn't work as keys there, so we'd have to do backflips to support them (like converting them to tuples).

**Comment by kain88-de** [comment]
Ah yeah I see. So the requirement is hashable best with a fast hashing method. Then the current way is OK.
