### ISSUE TITLE
Add  different tags to different data entries in a Treant

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#22]
I want to collect observables from several hundred observations into one `Treant` object. In the simulations different variables change. It would be nice if I could tag the data in a Treant instead of just adding tags to the Treant. I could use the tags to query for all simulations that fulfill a certain condition (eq integration time step, protein, ...)

I'm aware that I could achieve the same thing already with groups. But I only want to use one Treant object because I would like to have just one folder that I need to copy from the remote cluster to my laptop. If I understand groups correctly right now they just `link` to the Treant objects contained in them, which means I would still need to copy a lot of folders and have complicated rsync-rules to only copy the data I want.

So another solution for me would be that I can move Treant objects into the same location on disk as the `Group` is.

**Comment by dotsdl** [comment]
Hey @kain88-de , thanks for the interesting use case. If I understand it correctly, the tagging mechanism at the level of a `Treant` isn't granular enough, because you want to tag specific datasets that might be stored in it?

If so, as you pointed out, you could make many `Treant`s and add them to a `Group`, and to make them easy to move you could place them all inside the `Group`'s directory tree. That should work just fine, and makes complete sense here.

Another solution that needs an implementation yet is a metadata mechanism (see #15) for stored datasets. Perhaps that provides the granularity you're looking for?

**Comment by kain88-de** [comment]
> and to make them easy to move you could place them all inside the Group's directory tree.

How would that be done in python with datreant? 

> Another solution that needs an implementation yet is a metadata mechanism (see #15) for stored datasets. Perhaps that provides the granularity you're looking for?

yeah that looks close, even more general, then what I want.

**Comment by dotsdl** [comment]
>  How would that be done in python with datreant?

You can move a `Treant` around by setting its `location` property. This isn't well-documented at the moment because file locks aren't used to make the move, and any other instances of that `Treant` in other active python sessions will not find the moved file (#5), but that's probably not a concern for you here. 

Something to note: a `Treant`'s full path to its statefile goes like:

     /<location>/<name>/Treant.<uuid>.h5

where its `basedir` is `Treant.location + Treant.name`

**Comment by kain88-de** [comment]
I'll close this as I found out in the last year that I used the library wrong. I should create one treant per simulation. Which is what I'm doing now and I get pretty good milage out of datreant
