### ISSUE TITLE
set compression for hdf5 data storage

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#32]
I'm not sure if this exists yet but it would be nice if I could change the compression algorithm used by pytables to store my data.

**Comment by dotsdl** [comment]
It's not exposed, yeah, but I think it should be. We should pass kwargs through [`Treant.data.add`](https://github.com/datreant/datreant/blob/develop/datreant/limbs.py#L675) as well as [`Treant.data.append`](https://github.com/datreant/datreant/blob/develop/datreant/limbs.py#L837) and make it so that [`complevel` and `complib`](https://github.com/datreant/datreant/blob/develop/datreant/data/pddata.py#L54) get picked up by the underlying `pandas.HDFStore` methods.

**Comment by kain88-de** [comment]
It would also be nice if this could be set with a default when the Treant is created.

**Comment by dotsdl** [comment]
Closing here, since this has been moved to datreant/datreant.data#5
