### ISSUE TITLE
Create AggLimb `AggCategories`

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant.core#43]
We want an aggregation limb (`AggLimb`) for `Categories` similar to that which exists for `Tags`. It should give useful ways for dealing with the categories stored among the `Treant`s of a `Bundle`. I propose that it have at least the following:

1. the same API methods as `Categories`: `add`, `remove`, `clear`, `keys`.
2. a `groupby` method that gives groupings of `Treants` based on category values given keys.
3. a `__getitem__` that takes:
    1. a string giving a key returns a list of values in member order for that key; `None` is given for members in which they key is not present.
    2. a list of keys gives a list of lists given in order by key, each giving the values in member order; `None` as a value means they key is not present for the member (as above)
    3. a set of keys gives a dict of lists, with keys as keys and a list of values as above.
4. anything else I've failed to think of.

**Comment by dotsdl** [comment]
We definitely want to get this in before release (Wednesday). What's the status? Is there a working branch for this?

**Comment by sseyler** [comment]
Some basic progress has been made and I have the time to focus on it tonight and finish by tomorrow's release. I am working on the develop branch.

**Comment by sseyler** [comment]
Since `Categories` includes a `value()` method that returns the values for all of the categories (keys), would it be appropriate to have an analogous method in `AggCategories`?

A simplest implementation would simply return all of the values for each of the categories in a given collection in `AggCategories` as a (single, flattened) list; the values could also be returned as a list of lists, or even a dict of lists, in the same way to you suggest the `__getitem__` method behaves.

**Comment by dotsdl** [comment]
Feel free to do a `git checkout -b aggcategories` or similar and push that branch to this repo. Then I can more easily follow up if you want me to look at something. We can then immediately turn it into a PR and begin the code review for merge.

**Comment by sseyler** [comment]
In `AggTags`, the current implementation has

`
def __iter__(self):
        return self.all.__iter__()

def __len__(self):
    return len(self.all)
`

so that the sequence/iterable underlying the `AggTags` object is a list of the `Tags` that are *in common among all `Treant`s in the collection; as defined by the class property `all`, which "lists tags present among all Treants in collection", one can only iterate across the shared `Tags` among the `Treant`s, but *not over every unique tag* that's present in at least one `Treant` in the collection.

To iterate over every unique tag among the `Treant`s in the collection, `__iter()__`, `__len()__`, and similar methods must use the `any` property instead of `all`. Is this the desired behavior? Or is the current implementation the desired behavior and, if so, should `AggCategories` mirror this behavior?

**Comment by dotsdl** [comment]
This is up for debate. The idea here was that when looking at the tags of a collection of Treants, one should by default probably only show those tags that characterize the *whole* group (the tags that all Treants in the collection have), rather than any tag that is represented among the collection. It's a choice for which there is certainly an opposite argument.

Does that help?
