### ISSUE TITLE
limb data doesn't have limb specific filename

### ISSUE THREAD

**Issue by kain88-de** [datreant/datreant.core#61]
the _data_ limb creates `npData.h5` files. This opens possibility for name collisions when another limb wants to use the same name. IMHO the filename created from a limb should have some UUID attached to it a a unique identifier string for the limb.

**Comment by dotsdl** [comment]
This is a [``datreant.data``](https://github.com/datreant/datreant.data) issue. If it's not much trouble, would you mind moving this there? I think this is a good discussion to have, since that module very much is a quick-and-dirty convenience interface for common data structure storage.

**Comment by kain88-de** [comment]
I don't think this goes to the data sub-package. This is a very general problem. We have to ensure that every limb creates a unique file. If it is possible to do it guarantee this in *core* I would like to have it here.

For example you have two limbs `foo` and `bar` and decide add the same key to both. Coincidentally both write the same filename `blub.baz`

```python
s = dtr('obs')
s.attach('bar', 'foo')  # that would be cool if it worked!
s.bar['cool_data'] = np.random.randn(1000, 4)
s.foo['cool_data'] = {'boo' : 'blub', 'the-answer': 42, 'the-question': '?'}
```

Then the directory would look like this.

```
obs/
 +-- Treant.5680461c-414e-4c1b-b476-1ad0c879537d.json
 +-- cool_data/
     +-- blub.baz
```

`blub.baz` would contain the dictionary. 

It would be a big burden for the limb-developer to ensure that their filename is unique. Especially since they can't know which limbs are getting attached. Only the core object can know that and manage that.

**Comment by dotsdl** [comment]
@kain88-de I think I understand now. My opinion on the issue (open to revision) is that limbs fundamentally serve one of two purposes:

1. Manipulating data that gets stored in a Treant's state file.
2. Manipulating data that gets stored in a Treant/Tree's directory tree. These are limbs that can be attached directly to Trees, not just Treants.

For limbs that do (1), they need to uniquely place their data in the state file. We don't have this nicely documented yet somewhere, but for example the ``SimFile`` JSON spec in MDSynthesis looks roughly like this:

```
{
    'categories': {...}
    'tags': [...]
    'mdsynthesis': {...}
}
```
``Categories`` and ``Tags`` are both limbs that store their data in a state file, so they get their own key. The keys for limbs defined within the ``datreant`` namespace should not conflict, and the way we ensure this is simply by playing nice. All these components are in a sense all part of the same package, after all.

For limbs that do (2), we can be a bit looser. There may be limbs in the future that provide convenient ways of manipulating the filesystem objects within a Treant's tree, and these will always be able to see and work with whatever is present there. It's slightly more wild west, and I'm not sure where to draw any lines, really.

For the case of ``datreant.data``, we could change the naming convention to be a little less generic. Perhaps something like ``data.np.h5`` instead of ``npData.h5``? We get the name of the limb (``data``), the type of data stored (``np``, needed for ``data`` to know how to handle it easily), and the format (``h5``).

Does this help? Or am I still off base?
