### ISSUE TITLE
Tree.treant method?

### ISSUE THREAD

**Issue by gabrielelanaro** [datreant/datreant.core#92]
Hi, in my workflow, I usually explore a directory tree using the dtr.Tree class to avoid peppering the directories with state files. 

Then, when I want to save some state, I usually do

    dtr.Treant(tree['subtree']).data['energy'] = 128.0

To convert to a treant.

I was wondering, would it make sense to create a method so that I can chain very quickly (this avoids going back and forth to wrap between parentheses):

    tree['subtree'].treant().data['energy'] = 128

Not sure if method chaining aligns with datreant philosophy, and would like some feedback

**Comment by orbeckst** [comment]
In general I like this idea – upgrade the dumb tree to a talking-walking tree. 

What is supposed to happen if ``subtree``
- is already a `Treant` (probably just return it... will probably work automatically)
- is a sub-directory of a `Treant` (I can't remember what `Treant` does in this case – does it make a nested `Treant` and would this be what you want?)

**Comment by dotsdl** [comment]
@gabrielelanaro gave this one some thought, and came to the conclusion that what we currently have is probably best, since `Treant` is effectively a generic base class. If you're using a domain-specific package like `MDSynthesis`, you might have little use for `Treant`s. Instead, to make a `Treant`, `Group`, `Sim`, or any custom treant out of a `Tree`, you currently use the class itself to make it one.

Does this satisfy? I generally like the kind of chaining you describe myself, but I think here we might create a one-off inconsistency.

**Comment by gabrielelanaro** [comment]
@dotsdl Yes that's reasonable, it's important to keep things consistent
